In [1]:
import numpy as np

In [2]:
a = np.array([1, 6], [2, 8], [3, 11], [3, 10], [1, 7])

ValueError: only 2 non-keyword arguments accepted

In [3]:
a = np.array([[1,6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
a.shape

(5, 2)

In [9]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

In [10]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [11]:
a_centered.shape

(5, 2)

In [12]:
a_centered_tr = a_centered.transpose()
a_centered_tr

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [13]:
a_centered_sp = a_centered_tr[0] @ a_centered_tr[1]
a_centered_sp

8.0

In [14]:
a_centered_sp_cov = a_centered_sp / (len(a)-1)
a_centered_sp_cov

2.0

In [15]:
a_tr = a.transponse()
a_tr

AttributeError: 'numpy.ndarray' object has no attribute 'transponse'

In [16]:
a_tr = a.transpose()
a_tr

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [17]:
np.cov(a_tr)

array([[1. , 2. ],
       [2. , 4.3]])

In [18]:
import pandas as pd

In [19]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [20]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]}, columns=['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2    Толстый и тонкий    500
4          2      Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [21]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')

NameError: name 'books' is not defined

In [22]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')

In [23]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов    Толстый и тонкий    500
4          2       Чехов      Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [24]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name          book_title  price
3          2       Чехов  Толстый и тонкий    500
0          1    Тургенев         Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский               Гроза    370
2          1    Тургенев   Дворянское гнездо    350

In [25]:
authors_stat = pd.pivot_table(authors_price, values = 'price', index = 'author_name', aggfunc = {'price': [min, max, np.mean]})
authors_stat

max        mean    min
author_name                          
Островский   370.0  330.000000  290.0
Тургенев     450.0  366.666667  300.0
Чехов        500.0  475.000000  450.0